### ISSUE TITLE
Session namespace is non-unique

### ISSUE THREAD

**Issue by Teyras** [uestla/twigrid#15]
On line https://github.com/uestla/twigrid/blob/master/src/TwiGrid/DataGrid.php#L130, `$this->name` will always be `null` and is therefore redundant. Right now, I can't tell if it matters that the session namespace is the same for all datagrids, so take this as a heads up :)

**Comment by uestla** [comment]
You're right. Since the session namespace is in fact used only for CSRF token storing, this means one token would be the same for all datagrids in the application, which might and might not be an issue.

I'll fix this anyway, thanks for the report :-)
