### ISSUE TITLE
@deprecated method accessing

### ISSUE THREAD

**Issue by GEp1c** [uestla/TwiGrid#17]
Because of new Nette SmartObject strict is really important to change callback calls from ($this->function) to callback($this, 'function').

**For ex:**
`$latte->addFilter('translate', callback($this, 'translate'));`

**Comment by uestla** [comment]
I'll fix this after `Nette\Utils` 2.4 release. Thanks for reminding.

**Comment by GEp1c** [comment]
So, please change this:

`	"require" : {
		"php": ">= 5.3.0",
		"nette/http": "^2.3",
		"nette/forms": "^2.3",
		"nette/utils": "^2.3",
		"nette/application": "^2.3"`

To this:
`	"require" : {
		"php": ">= 5.3.0",
		"nette/http": "~2.3",
		"nette/forms": "~2.3",
		"nette/utils": "~2.3",
		"nette/application": "~2.3"`

Cause it forces automaticly to download 2.4RC1
