### ISSUE TITLE
composer dependency forcing to download 2.4RC1

### ISSUE THREAD

**Issue by GEp1c** [uestla/TwiGrid#18]
`	
"require" : {
	"php": ">= 5.3.0",
	"nette/http": "^2.3",
	"nette/forms": "^2.3",
	"nette/utils": "^2.3",
	"nette/application": "^2.3"
`

To this:
`	
"require" : {
	"php": ">= 5.3.0",
	"nette/http": "~2.3",
	"nette/forms": "~2.3",
	"nette/utils": "~2.3",
	"nette/application": "~2.3"
`

Cause it forces automatically to download 2.4RC1

**Comment by uestla** [comment]
I think it has to do with "minimum-stability" directive... Closing.
