### ISSUE TITLE
end() expects parameter 1 to be array, null given

### ISSUE THREAD

**Issue by GEp1c** [uestla/TwiGrid#19]
Pokud chci využívat filtry, a nesplním jejich podmínky, vypíše se alert (správně), ale pokud projde vstup input buttonu přes form rules a je hodnota validní, vypíše to chybu end() expects parameter 1 to be array, null given na řádku označeném níže. Využívám TwiGrid již dlouho, několik chyb jsem po po 2.4RC odstranil a zašlu pak patch, každopádně přes tuto chybu se dostat ani já nedokáži.

```
{define filter-cell}

	<th n:class='filter-cell, ($hasControl = isset($form["filters-criteria-$column"])) && !($isControl = ($form["filters-criteria-$column"] instanceof Nette\Forms\IControl)) ? alert-warning'>
	{if $hasControl && $isControl}
		{php }{input filters-criteria-$column, class => 'form-control'} <--- Zde
	{else}
		&nbsp;
	{/if}
	</th>

{/define}
```

Každopádně, pokud se s aktuální verzí vyzkouší filtrování, deprecated problémů je opět více. Např. co vyhodí User Notice:

```
value => $template->getValue($record, $name, FALSE)
```

či toto (Accessing parameters via. $template->param is deprecated, nyní v Nette/Latte neexistuje způsob jak v Latte nastavit parametr, jedině skrze renderBlock).

```
{var $template->hasData = (bool) $iterations}
```

**Comment by uestla** [comment]
Co se vykreslování form inputů uvnitř snippetu týče, myslím, že to asi nedokážu vyřešit - snažil jsem se to nadhodit na fóru, ale ani `snippetArea` mi nepomohla - vlastně jsem o ní ani nevěděl a nevím, jak má fungovat...

Zbytek bych měl mít opraven, ale asi to nemá cenu vydávat, když nefungují snippety - jediné řešení je nepoužívat AJAX, což totálně zabije použitelnost...

**Comment by GEp1c** [comment]
Tak to pushni a já se na to zkusím podívat.

**Comment by uestla** [comment]
Pushnuto :-)

Díky.

**Comment by GEp1c** [comment]
https://forum.nette.org/cs/26400-nette-2-4-snippety-ve-formulari-jako-komponente

S pozdravem,
Kulíšek Patrik.

*Tel.:* +420 602 145 458
*Email:* kulisek.patrik@gmail.com
*WWW:* http://gepic.cz

2016-05-27 9:25 GMT+02:00 uestla <notifications@github.com>:

**Comment by uestla** [comment]
Tak jsem to zkusil vyřešit podle [Davidovy rady](https://forum.nette.org/cs/26250-pojdte-otestovat-nette-2-4-rc?p=2#p175147) a vypadá to funkčně :-)

Je to sice workaround, ale hlavně, že to funguje. Přidal jsem ještě pár dalších úprav a pushnul. V současné době to tedy běží s masterem 2.4.

**Comment by GEp1c** [comment]
Ahoj, je možné to označit jako 6.0.9? Kvůli composeru. Děkuju.

S pozdravem,
Kulíšek Patrik.

*Tel.:* +420 602 145 458
*Email:* kulisek.patrik@gmail.com
*WWW:* http://gepic.cz

Dne 31. května 2016 22:01 uestla <notifications@github.com> napsal(a):

**Comment by GEp1c** [comment]
Jinak samozřejmě díky moc za ochotu, otestuji na jednom z projektů a popř.
podám feedback.

S pozdravem,
Kulíšek Patrik.

*Tel.:* +420 602 145 458
*Email:* kulisek.patrik@gmail.com
*WWW:* http://gepic.cz

Dne 31. května 2016 23:00 Patrik Kulíšek <kulisek.patrik@gmail.com>
napsal(a):

**Comment by GEp1c** [comment]
Beru zpět, nebyla potřeba, projekt je stále v min.stability - dev

S pozdravem,
Kulíšek Patrik.

*Tel.:* +420 602 145 458
*Email:* kulisek.patrik@gmail.com
*WWW:* http://gepic.cz

Dne 31. května 2016 23:00 Patrik Kulíšek <kulisek.patrik@gmail.com>
napsal(a):
