### ISSUE TITLE
Chybějící buňka v patičce

### ISSUE THREAD

**Issue by igorpocta** [uestla/TwiGrid#21]
Ahoj, když si přidám inline edit, tak se rozhodí rozložení tabulky, resp. v patičce chybí buňka posledního sloupce.

![twigrid](https://cloud.githubusercontent.com/assets/6266721/15848433/46b52a7e-2c8d-11e6-9077-ffa6b96b225a.PNG)

**Comment by igorpocta** [comment]
Prozatím jsem si poradil tak, že jsem si redefinoval footer a colspan upravil následovně:
{$hasInlineEdit ? $columnCount + 1 : $columnCount}

**Comment by uestla** [comment]
Děkuju, tohle mi uniklo.
