### ISSUE TITLE
"multisort" class in all headers

### ISSUE THREAD

**Issue by tprochazka** [uestla/TwiGrid#31]
In latest version 11.2.1 is one strange thing.
All column headers has class 'multisort' also when column doesn't have allowed sorting by `setSortable()`, so all columns has additional space on the right, but without sorting icon, which looks weird, if you are not using sorting. I found that it is possible turn it of by `setMultiSort(false)`.

**Comment by uestla** [comment]
Thanks! Fixed in master and cherry-picked for version `11.2.2` :-)
