### ISSUE TITLE
Compatibility with PHP 7.0.19

### ISSUE THREAD

**Issue by tprochazka** [uestla/TwiGrid#34]
Latest version currently available for Raspberry Pi is 7.0.19.

I tried latest version and it crash just because of "?" used here `public function getColumns(): ?\ArrayIterator` or `public function getItemsPerPage(): ?int`.  This is some new syntax of 7.1? I did not found any information about it yet. But without it, it normally works on booth versions.

**Comment by tprochazka** [comment]
So, there is more issue, for example  : void as return type.
I will need to go back to the older version.

**Comment by uestla** [comment]
That is correct. Latest stable version for PHP5.6 is 11.2.1 as stated in [this release](https://github.com/uestla/TwiGrid/releases/tag/11.2.1).

**Comment by uestla** [comment]
Oops... I also stated that I'll release new major version after rewriting the core to PHP7 which I did not :-/

My bad, sorry about that.

**Comment by tprochazka** [comment]
I think that this can be closed ;-)
