### ISSUE TITLE
Creating default object from empty value (PHP 7.0.10 / TwiGrid 11.2.0)

### ISSUE THREAD

**Issue by GEp1c** [uestla/TwiGrid#35]
![image](https://user-images.githubusercontent.com/16386245/30243101-f99597f8-95a2-11e7-8782-5d2a2470b17b.png)

This warning shows up when I try to do some AJAX action (simply call presenter's signal) where I don't need to redraw any snippet (I just save some data to database) on page with rendered TwiGrid. When I add `$this->redrawControl('dummySnippet')` the problem dissapears.

**Comment by GEp1c** [comment]
EDIT: Problem occurs only if there is more than 1 TwiGrid rendered on the page. Simply if I render 3 grids, only first one get in `$this->payload` object `\stdClass`, other 2 grids get `null`. 

The problem is caused there:
https://github.com/uestla/TwiGrid/blob/master/src/TwiGrid/DataGrid.php#L158

**Comment by uestla** [comment]
Ah, you're right. Also thanks for the investigation! :-)

Could you prepare a PR with fix, please?

**Comment by GEp1c** [comment]
PR sended, I think it should work as expected cause you are running only 1 payload at the time for only 1 grid.

**Comment by uestla** [comment]
Continuing in PR - https://github.com/uestla/TwiGrid/pull/36

Closing this.
