### ISSUE TITLE
build() is called too early in component lifecycle

### ISSUE THREAD

**Issue by tprochazka** [uestla/TwiGrid#39]
I need to react on a signal by `handleDisplay($year, $month)` method, but it is not possible, because `build()` method is evaluated before a signal is processed. It is the correct behavior? I would expect that would be possible to change the grid configuration based on signals.

**Comment by uestla** [comment]
`build()` is called when the grid is attached to presenter.

Your `handleDisplay()` is defined in the datagrid class? What do you mean by "changing the grid"? Please send some code example of your usage and desired result.

**Comment by tprochazka** [comment]
I need to change the number of columns by signal, so I need to have already processed signal when I'm creating $this->addColumn.

The only solution I found so far is not using signal and handleDisplayMethod, but simply send all the necessary information directly in the component factory.

**Comment by uestla** [comment]
Thing is columns are components attached to grid. Changing the component structure on signal is not what I would consider clean solution.

Sending the information through component factory is the way to go I think 👍

**Comment by tprochazka** [comment]
OK. Thanks. I will do it in this way.

**Comment by uestla** [comment]
Closing as resolved.
